version: '3.4'

services:
  homespeaker.client.web:
    image: ${DOCKER_REGISTRY-}homespeakerclientweb
    build:
      context: .
      dockerfile: HomeSpeaker.Client.Web/Dockerfile


  homespeaker.server:
    image: ${DOCKER_REGISTRY-}homespeakerserver
    build:
      context: .
      dockerfile: HomeSpeaker.Server/Dockerfile


  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/grocy:/config
    ports:
      - 4321:80
    restart: unless-stopped
