version: '3.4'

services:
  homespeaker.server2:
    container_name: homespeaker.server2
    image: ${DOCKER_REGISTRY-}homespeakerserver2
    build:
      context: .
      dockerfile: HomeSpeaker.Server2/Dockerfile
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    devices:
    - /dev/snd:/dev/snd
    volumes:
    - "/home/piuser/music:/music"
    - "/home/piuser/cert:/certs"
    depends_on:
    - jaeger
    environment:
    - MediaFolder=/music
    - ALSA_CARD=Headphones
    - ASPNETCORE_URLS=https://+443;http://+:8080
    #- ASPNETCORE_Kestrel__Certificates__Default__Password=ThisIsMySslCertPassword23
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/certificate.pfx

  jaeger:
    image: jaegertracing/all-in-one:1.41
    environment:
    - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    - COLLECTOR_OTLP_ENABLED=true
    ports:
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686 #web UI
    - 4317:4317
    - 4318:4318
    - 14250:14250
    - 14268:14268
    - 14269:14269
    - 9411:9411


