version: '3.4'

services:
  homespeaker.server2:
    image: ${DOCKER_REGISTRY-}homespeakerserver2
    build:
      context: .
      dockerfile: HomeSpeaker.Server2/Dockerfile
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - "/home/piuser/music:/music"
    - "/home/piuser/.aspnet/https:/certs"
    environment:
    - MediaFolder=/music
    - ALSA_CARD=Headphones
    - ASPNETCORE_URLS=https://+:443;http://+:80
    - ASPNETCORE_Kestrel__Certificates__Default__Password=ThisIsMySslCertPassword23
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/aspnetapp.pfx