version: '3.4'

services:
  homespeaker.server2:
    container_name: homespeaker.server2
    image: ${DOCKER_REGISTRY-}homespeakerserver2
    build:
      context: .
      dockerfile: HomeSpeaker.Server2/Dockerfile
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    devices:
    - /dev/snd:/dev/snd
    volumes:
    - "/home/piuser/music:/music"
    - "/home/piuser/cert:/certs"
    depends_on:
    - jaeger
    environment:
    - MediaFolder=/music
    - ALSA_CARD=Headphones
    - SqliteConnectionString=Data Source=/music/HomeSpeaker.db
    - ASPNETCORE_URLS=https://+443;http://+:8080
    #- ASPNETCORE_Kestrel__Certificates__Default__Password=ThisIsMySslCertPassword23
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/certificate.pfx
    - FFMpegLocation=/usr/bin/ffmpeg
    - OtlpExporter=http://jaeger:4317
    networks:
      jaegernet:

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.44
    environment:
    - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    - COLLECTOR_OTLP_ENABLED=true
    ports:
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686 #web UI
    - 4317:4317
    - 4318:4318
    - 14250:14250
    - 14268:14268
    - 14269:14269
    - 9411:9411
    networks:
      jaegernet:

    #  docker rm -f jaeger ; docker run -d --name jaeger -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 -e COLLECTOR_ZIPKIN_ALLOWED_ORIGINS=* -p 13133:13133 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 14250:14250 -p 9411:9411 -p 4317:4317 --restart=unless-stopped jaegertracing/opentelemetry-all-in-one


networks:
 jaegernet:
