version: '3.5'

services:
  homespeaker.client.web:
    image: ${DOCKER_REGISTRY-}snowjallen/homespeakerwebclient:${BuildID}
    ports:
     - 80:80
    networks:
     homenet:
    restart: unless-stopped
    depends_on:
    - homespeaker.server
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - HomeSpeaker.Server=http://homespeaker.server

  homespeaker.server:
    image: ${DOCKER_REGISTRY-}snowjallen/homespeakerserver:${BuildID}
    ports:
     - 8080:80
    networks:
     homenet:
    restart: unless-stopped
    devices:
    - /dev/snd:/dev/snd
    volumes:
    - "/home/pi/Music:/music"
    - "/home/pi/apk:/apk"
    environment:
    - MediaFolder=/music
    - ApkFolder=/apk
    - ASPNETCORE_ENVIRONMENT=Development
    - ALSA_CARD=Headphones


networks:
  homenet:
