version: '3.5'

services:
  homespeaker.client.web:
    image: 192.168.1.133:5555/homespeakerwebclient:arm32v7
    ports:
     - 80:80
    networks:
     homenet:
    restart: unless-stopped
    depends_on:
    - homespeaker.server
    volumes:
    - "/home/pi/apk:/apk"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ApkFolder=/apk
    - HomeSpeaker.Server=http://homespeaker.server

  homespeaker.server:
    image: 192.168.1.133:5555/homespeakerserver:arm32v7
    ports:
     - 8080:80
    networks:
     homenet:
    restart: unless-stopped
    devices:
    - /dev/snd:/dev/snd
    volumes:
    - "/home/pi/Music:/music"
    environment:
    - MediaFolder=/music
    - ASPNETCORE_ENVIRONMENT=Development
    - ALSA_CARD=Headphones


networks:
  homenet:
