version: '3.5'

services:
  homespeaker:
    image: ${DOCKER_REGISTRY-}snowjallen/homespeaker:${BuildID}
    ports:
     - 80:80
    networks:
     homenet:
    restart: unless-stopped
    devices:
    - /dev/snd:/dev/snd
    volumes:
    - "/home/pi/Music:/music"
    environment:
    - MediaFolder=/music
    - ASPNETCORE_ENVIRONMENT=Development

  # reverseProxy:
  #   image: linuxserver/swag:latest
  #   environment:
  #    - TZ=America/Denver
  #    - URL=beta.sanpetepantry.org
  #    #- SUBDOMAINS=beta
  #    - VALIDATION=http
  #    #- STAGING=true
  #   volumes:
  #    - ./default.conf:/config/nginx/site-confs/default
  #    - cachedcerts:/config
  #   ports:
  #    - 443:443
  #    - 80:80
  #   restart: unless-stopped
  #   networks:
  #    homenet:

networks:
  homenet:

volumes: 
  cachedcerts: 