name: Docker Image CI

on:
  push:
    #tags:
    #- '*'
  # To have GitHub Actions deploy a new version, create a new tag
  # git tag -a yyyy.m.d -m yyyy.m.d
  # Then push those tags
  # git push --tags
  # Then a new version will be deployed on the self-hosted runner.

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: kill any running brightness api
      run: pkill -f brightness_api.dll || true

    - name: publish brightness api
      run: |
          cd brightness_api
          dotnet publish -c Release -o publish
    - name: run brightness api
      run: |
          cd brightness_api
          sudo cp brightness_api.service /etc/systemd/system/brightness_api.service
          sudo systemctl daemon-reload
          sudo systemctl start brightness_api
  
    - name: Docker compose pull
      run: docker-compose pull

    - name: Docker compose down
      run: docker-compose down

    - name: Docker compose up
      env:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1
      run: docker-compose up -d --build
