name: Docker Image CI

on:
  push:
    tags:
    - '*'
  # To have GitHub Actions deploy a new version, create a new tag
  # git tag -a yyyy.m.d -m yyyy.m.d
  # Then push those tags
  # git push --tags
  # Then a new version will be deployed on the self-hosted runner.
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Restart the docker compose
      run: docker-compose up -d --build
