name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Get smart tag
      id: prepare
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: snowjallen/homespeaker
        tag_with_sha: true
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2.2.1      
      with:
        file: HomeSpeaker.Web/Dockerfile
        push: true
        platforms: linux/arm/v7,linux/armv7,linux/arm32v7
        tags: ${{ steps.prepare.outputs.tag }}
        build-args: |
          exampleArg=exampleArgValue
          otherArg=$GITHUB_SHA
          
    - name: Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.LINODE_SERVER }}
        username: ${{ secrets.LINODE_USER }}
        password: ${{ secrets.LINODE_PASSWORD }}
        localDir: scripts
        remoteDir: scripts

    - name: Start the service
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:      
        command: cd scripts && /usr/bin/powershell/pwsh ./restart.ps1 -tag ${{ steps.prepare.outputs.tag}}
        host: ${{ secrets.LINODE_SERVER }}
        username: ${{ secrets.LINODE_USER }}
        password:  ${{ secrets.LINODE_PASSWORD }}    

